import os
import sys
import re
from typing import List

from utils import append_test_method_to_file, extract_package_path
from test_compiler import check_if_test_compiles
from test_extractor import extract_tests_from_file


def rename_classes_in_file(file_path: str) -> None:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    pattern = r'(public\s+class\s+)(\w+)(\s*\{)'
    replacement = r'\1\2Augmented\3'
    new_content = re.sub(pattern, replacement, content)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)


def add_augmented_to_constructor_subject(file_path: str, subject_name: str) -> None:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    escaped_subject = re.escape(subject_name)
    pattern_regex = rf'\b({escaped_subject})(\b\s+\w+\s*=\s*new\s+)({escaped_subject})(\s*\()'
    replacement = r'\1Augmented\2\3Augmented\4'
    new_content = re.sub(pattern_regex, replacement, content)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)


def rename_test_methods(test_methods: List[str], new_name: str) -> List[str]:
    name_pattern = r'public void \w+\(\)'
    return [
        re.sub(name_pattern, f'public void {new_name}{i}()', test_method)
        for i, test_method in enumerate(test_methods)
    ]

# TODO: fix the cases like Sout() etc, que reemplaza.


def replace_method_calling(test_methods: List[str], subject_package: str) -> List[str]:
    constructor_pattern = r'new\s+(?!' + \
        re.escape(subject_package) + r'\.)([A-Z]\w*)\('
    static_call_pattern = r'(?<!' + \
        re.escape(subject_package) + r'\.)\b([A-Z]\w*)\.'
    type_declaration_pattern = r'(?<!@)(?<!' + \
        re.escape(subject_package) + r'\.)\b([A-Z]\w*)\b'

    new_tests = []
    for test in test_methods:
        unqualified_constructor = re.search(constructor_pattern, test)
        unqualified_static = re.search(static_call_pattern, test)
        unqualified_type = re.search(type_declaration_pattern, test)

        if not (unqualified_constructor or unqualified_static or unqualified_type):
            new_tests.append(test)
        else:
            test = re.sub(constructor_pattern,
                          f'new {subject_package}.\\1(', test)
            test = re.sub(static_call_pattern, f'{subject_package}.\\1.', test)
            test = re.sub(type_declaration_pattern,
                          f'{subject_package}.\\1', test)
            new_tests.append(test)
    return new_tests


def add_tests_to_driver(file_path: str, test_methods: list) -> None:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    if_block_pattern = r'if\s*\(\s*hadFailure\s*\)\s*\{'

    new_tests = "// Tests generated by LLM".join([
        f"""
        try {{
            t0.{test}();
        }} catch (Throwable e) {{
            hadFailure = true;
            e.printStackTrace();
        }}
        """ for test in test_methods
    ])

    new_content = re.sub(if_block_pattern, new_tests +
                         r'\g<0>', content)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)


def main() -> None:
    if len(sys.argv) < 4:
        print("Usage: python script.py <destination_test_file> <destination_test_driver_file> <source_test_file> <subject_file>")
        sys.exit(1)

    destination_test_file, test_driver_file, source_test_file, subject_file = sys.argv[1:5]
    test_methods = extract_tests_from_file(source_test_file)
    subject_package = extract_package_path(subject_file)

    rename_classes_in_file(destination_test_file)
    rename_classes_in_file(test_driver_file)

    tester_class_name = os.path.basename(
        destination_test_file).replace('Augmented.java', '')
    add_augmented_to_constructor_subject(test_driver_file, tester_class_name)

    if not test_methods:
        return
    test_methods = rename_test_methods(test_methods, 'llmTest')
    test_methods = replace_method_calling(test_methods, subject_package)

    compilable_test_methods = []
    for test_method in test_methods:
        if check_if_test_compiles(destination_test_file, subject_file, test_method):
            append_test_method_to_file(destination_test_file, test_method)
            compilable_test_methods.append(test_method)

    compilable_test_names = [re.search(
        r'public void (\w+)\(\)', test).group(1) for test in compilable_test_methods]
    add_tests_to_driver(test_driver_file, compilable_test_names)


if __name__ == "__main__":
    main()
